[report]
# Output formats for coverage reports
out = ["Html", "Lcov", "Xml"]

# Include all source files
include-tests = true
run-types = ["Tests", "Doctests"]

# Exclude certain files/directories
exclude = [
    "target/*",
    "tests/*"  # Don't include test files in coverage
]

# Coverage options
follow-exec = true
count = true
all-features = true

# HTML output directory
output-dir = "coverage"

# Timeout for test execution
timeout = "120s"

[html]
title = "AI Screenshot Analyzer Coverage Report"